apiVersion: v1
kind: Service
metadata:
  name: kube-dns-udp
  namespace: kube-system
  labels:
    k8s-app: kube-dns
  annotations:
    metallb.universe.tf/allow-shared-ip: kube-dns
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  externalTrafficPolicy: Cluster
  ports:
    - port: 53
      protocol: UDP
      targetPort: 53
