---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: redis-cart
namePrefix: prod-
commonAnnotations:
  stand: PROD
namespace: hipster-shop-prod
bases:
  - ../../base
