apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - env:
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice:3550
        - name: CURRENCY_SERVICE_ADDR
          value: currencyservice:7000
        - name: CART_SERVICE_ADDR
          value: cartservice:7070
        - name: RECOMMENDATION_SERVICE_ADDR
          value: recommendationservice:8080
        - name: CHECKOUT_SERVICE_ADDR
          value: checkoutservice:5050
        - name: SHIPPING_SERVICE_ADDR
          value: shippingservice:50051
        - name: AD_SERVICE_ADDR
          value: adservice:9555
        image: 99francs/paymentservice:v0.0.1
        name: paymentservice
