---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend
spec:
  rules:
    - host: frontend.35.192.25.216.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: {{ .Values.service.port }}
