apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fornted
  name: fornted
spec:
  containers:
  - image: 99francs/fronted:latest
    name: fornted
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
